Sorting Algorithms/couting_sort.cpp

Hi,
This PR to add the counting sort algorithm
Assigned with issue #14 
I hope this helps other developers
Thanks

Counting Sort Added

---

Numbers/Basic_Programs/Leap year program using functions.c
Numbers/Basic_Programs/armstrong_number.c
Numbers/Basic_Programs/leap-year.c
Numbers/Basic_Programs/prime_number.c
Numbers/Basic_Programs/prime_number_using_recursion.c
Python Programs/hello world.py

@smv1999 i created hello world in python because we start in python just now so start from level 1 now i added some medium and hard level programs in python because of starting so thats why i added hello world

Basic Programs / Python

---

Sorting Algorithms/radix_sort.cpp

Hello,
This PR to add the radix sort algorithm
I hope this helps other developers
Assigned with issue #17 
Thanks

Radix Sort Added

---

General Questions/Plus_One.cpp

Hello,
This PR to add a new general question for a `LeetCode` problem.
I hope this help other developers.
Thanks

General Question Added [LeetCode Problem]

---

Strings/Reverse_vowels_of_a_string.cpp

Added the following files in Strings/
- Reverse_vowels_of_a_string.cpp
Closes #47

[feature-1] Added Reverse Vowels of a String program in CPP

---

2D Arrays/StairCaseSearch.py

Added the following files in 2D Arrays/
- StairCaseSearch.py
Closes #49

[feature-1] Added StairCase Search in Python

---

2D Arrays/sum_of_all_submatrices_3.cpp

The following files were added in 2D Arrays/
- sum_of_all_submatrices_2.cpp
Closes: #60

[feature-1] sum_of_all_submatrices_3.cpp file added

---

2D Arrays/sum_of_matrix_Q_queries.cpp

The following files were added in the folder 2D Arrays/
- sum_of_all_matrix_Q_queries.cpp

[feature-1] Added Sum of matrix for Q queries in CPP

---

Arrays/Array Reversal.c

I Have readed the [contributing.md](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)
and follow the rules..
```javascript
if(you Love)
{
Thanks for let me to contribute😊😊
Happy Coding! 👨‍💻
}
```

Array Reversal added

---

Arrays/merge_two_sorted_arrays.cpp

Closes: #65 
Following files were added in Arrays/ :
- merge_two_sorted_arrays.cpp

[feature-1] Added Merge two sorted arrays without using extra space in CPP

---

Data Structures/Trees/min_bs.cpp

Minimun Node in BST, cpp program

---

2D Arrays/count_negative_in_sorted_matrix.cpp

Closes: #71 
The following files were added in 2D Arrays/:
- count_negative_in_sorted_matrix.cpp

[feature-1] Count Negatives in Sorted Matrix optimised approach added in CPP

---

Arrays/Array Reversal.py
Arrays/CommonElements.py
Arrays/duplicates_in_array.py
Arrays/remove_duplicates_from_sorted_array.py
Arrays/subset_of_array.py

Added python solution in the following question files -
Array Reversal.py
CommonElements.py
duplicates_in_array.py
remove_duplicates_from_sorted_array.py
subset_of_array.py

Added Python programs Part - 1

---

Numbers/FindDivisors.py
Numbers/LargerNumber.py
Numbers/factorial_of_a_number.py
Numbers/factorial_of_a_number_recursion.py
Numbers/fibonacci_series.py

Added python solution in the following question files -
factorial_of_a_number_recursion.py
factorial_of_a_number.py
fibonacci_series.py
FindDivisors.py
LargerNumber.py
This PR closes #78

Added Python programs Part - 2

---

General Questions/pattern_1.py
General Questions/pattern_2.py
General Questions/pattern_3.py
General Questions/pattern_4.py
General Questions/pattern_5.py

Added python solution in the following question files -
pattern_1.py
pattern_2.py
pattern_3.py
pattern_4.py
pattern_5.py
This PR closes #80

Added Python programs Part - 3

---

OOPs/Polymorphism/function_overloading.cpp
OOPs/Readme.md

Hey,
I have added function overloading as well as created a readme to from where you can get any program by just clicking on the program link
Please review it ..
Closes: #83

Added Function overloading

---

2D Arrays/Set Matrix Zero.cpp

Create Set Matrix Zero

---

DSA 450 GFG/max_and_min_of_array.py
DSA 450 GFG/move_all_neg_numbers.py
DSA 450 GFG/reverse_an_array.py

Added Python solutions for DSA-450 Problems
- Reverse an array
- Find the maximum and minimum element in an array
- Move all the negative elements to one side of the array

Completed issue - 91 : Added python code for DSA 450

---

Data Structures/Linked Lists/segregate_even and_odd_nodes_LL.cpp
Greedy/n_meetings_in_a_room.cpp

Added the problem for segregation of  odd /even nodes of a linked list and made a sub-directory for greedy algorithms, adding N meetings in a room problem.
Added approach  and problem statement as comment in the code itself. Please review the PR.

Added one Linked list and one greedy problem

---

Data Structures/Linked Lists/Swap_nodes.py

Created a Swap Nodes of Linked List without Swapping data code in Python

---

DSA 450 GFG/chocolate_distribution.py

- Added Code for Chocolate Distribution Problem in Python

Chocolate Distribution Problem-Python

---

DSA 450 GFG/row_with_max_ones.py
DSA 450 GFG/search_elements_in_a_matrix.py

- Added code for matrix problems in DSA-450 in Python
-  Link to the problems:
- Search element in a matrix  : https://leetcode.com/problems/search-a-2d-matrix/
- Max Ones in a row :  https://practice.geeksforgeeks.org/problems/row-with-max-1s0023/1#
- Closes issue #99

Added code for Matrix problems in DSA-450 in Python , closes isssue -99

---

Searching Algorithms/Ternary_search.c

Hey @smv1999,
I have added Ternary search in c language
Please review it 
closes: #96
Thanks

added Ternary search.c

---

README.md

Hey @smv1999,
I have fixed the bug in the follower label
Please review it 
closes: #105 
Thanks

fix bug in follower label

---

Dynamic Programming/CoinChange.py

Added Python Solution for Coin Change Problem
Link to the Problem : https://leetcode.com/problems/coin-change/
Closes #110

Python Solution for Coin Change Problem in DP

---

Strings/Count_word.c

Hey @smv1999 
Please review it 
closes: #104 
Thanks

Added Count word.c Program

---

Sorting Algorithms/insertion_sort.py
Sorting Algorithms/selection_sort.py

Added Python solution for Insertion sort and selection sort 
Closes #113

Python solution for insertion sorrt and selection sort

---

DSA 450 GFG/merge_intervals.py

Add Python solution for merged intervals in dsa450

---

DSA 450 GFG/spiral_matrix.py

Python solution for Spiral matrix in DSA450

---

Hashing/sequence_pair_weight.cpp

Started the Hashing Problems Directory with solution to one problem from Codeforces Online Judge.

Creating Hashing Directory with one problem

---

DSA 450 GFG/BuyandSell.py

Python solution for Buy and sell stock in DSA 450

---

DSA 450 GFG/maxones.py

Python solution for max-ones-in-a-row-in-the-matrix in DSA450

---

DSA 450 GFG/next_permutation.py

Python solution for next permutation

---

Dynamic Programming/knapsack_01.cpp

Added solution to 0/1 Knapsack using memorization in C++, the question and the approach  as been explained inside the code file as comments before the initial imports.

added solution for 0_1 knapsack

---

Hashing/chef_and_subarrays.cpp

This is a problem that requires some Observation related to periodicity and Hashing to be solved.. Review and add if ok.

Recent problem from Codechef that uses Hashing

---

Data Structures/Linked Lists/Doubly Linked List/delete_at_begin.cpp

I have added delete_at_begin.cpp file inside the Doubly Linked Lists folder, which deletes a node from the beginning.
Closes: #137

Added program to Delete a Node from the beginning in a Doubly Linked Lists

---

Data Structures/Linked Lists/Doubly Linked List/delete_at_end.cpp

I have added delete_at_end.cpp file inside the Doubly Linked Lists folder, which deletes a node from the end.
Closes: #141

Added Delete at the end of the Doubly Linked Lists

---

DSA 450 GFG/snake_pattern.py

Python solution for Snake pattern in matrix in DSA450

---

Sorting Algorithms/Bubble_sort.c

Hey @smv1999,
I have added Bubble sort.
Please review it.
Closes: #149.
Thanks...

Added Bubble sort

---

Data Structures/Linked Lists/Circular Linked Lists/insert_at_end.cpp

Added insert_at_end.cpp file which adds a node to the end of the Circular Linked Lists.
Closes: #153

Added Insert at End in Circular Linked Lists

---

DSA 450 GFG/HeightOfBinTree.py

Python solution for Height of Binary tree in DSA 450

---

Data Structures/Linked Lists/Circular Linked Lists/delete_at_begin.cpp

The program is to delete a node from the head of the Circular Linked Lists.
Closes: #156

Delete at the Head of the Circular Linked Lists

---

DSA 450 GFG/DiameterOfBinTree.py

Python solution for Diameter of Binary tree in dsa 450

---

DSA 450 GFG/InOrderTraversal-rec.py
DSA 450 GFG/InorderTraversal-Iterative.py

Both iterative and recursive 
CLoses #163

Python solution for Inorder Traversal 

---

Data Structures/Graphs/isGraphBipartite.cpp

Please review the PR. And suggest changes if any.

isGraphBipartite algorithm added

---

DSA 450 GFG/post-ord-iterative.py
DSA 450 GFG/post-order-rec.py

Python solution for Post order reversal, iterative and recursive 

---

Data Structures/Linked Lists/Circular Linked Lists/delete_at_end.cpp

The program deletes a node from the end of the Circular Linked List
Closes: #160

Added Delete at end in Circular Linked List

---

Data Structures/Linked Lists/Circular Linked Lists/reverse.cpp

The program reverses the Circular Linked Lists iteratively
Closes: #173

Added Iterative Reverse in Circular Linked Lists

---

DSA 450 GFG/vertical_order_traversal.py

Python solution for Vertical order traversal

---

Data Structures/Linked Lists/Circular Linked Lists/recursive_reverse.cpp

The program reverses the Circular Linked Lists recursively
Closes: #174

Added Recursive Reverse in Circular Linked Lists

---

Data Structures/Linked Lists/Circular Doubly Linked Lists/insert_at_end.cpp

This program creates a DCLL node and adds it at the end of the List.
Closes: #178

Added insert a Node at the End of the Circular Doubly Linked Lists

---

DSA 450 GFG/DeleteNodeinBST.py

Python solution for deleting a node in BST - DSA 450

---

DSA 450 GFG/BTtoBST.py

Python solution for converting BT to BST in DSA 450

---

DSA 450 GFG/lowest_common_ancestor.py

Python solution for lowest common ancestor in DSA 450

---

Data Structures/Linked Lists/Circular Doubly Linked Lists/insert_at_begin.cpp

This program creates a DCLL node and adds it at the head of the List.
Closes: #179

Added Insert At Begin in Circular Doubly Linked Lists

---

Data Structures/Linked Lists/Circular Doubly Linked Lists/delete_at_begin.cpp

The problem deletes a node from the head of the doubly circular linked lists.
Closes: #189

Added Delete At the Head of the Doubly Linked Lists

---

Data Structures/Linked Lists/Circular Doubly Linked Lists/delete_at_end.cpp

The problem deletes a node from the end of the doubly circular linked lists.
Closes: #188

Added Delete At the End of the Circular Doubly Linked Lists

---

Data Structures/Linked Lists/Circular Doubly Linked Lists/reverse.cpp

The problem is to reverse the Circular Doubly Linked Lists iteratively.
Closes: #195

Added Iterative Reverse in Circular Doubly Linked Lists

---

Arrays/KLargestpairs.py
Arrays/ShortestContinuousSubarray.py
Numbers/RomantoInteger.py
Strings/removePalindromicSubsequences.java

Closes issue #210 
@smv1999 
2 problems related to arrays(shortest unsorted continuous subarray, K largest pairs), 1 of strings(to remove palindromic subsequences) and 1 of numbers(convert roman numeral to its equivalent integer)

added 4 new programs 

---

Data Structures/Graphs/BFSTraversal.cpp

Added BFS Graph Traversal using Adjacency List Representation.

Added BFS Graph Traversal

---

Sorting Algorithms/quick_sort.py

I have added the python program for quick sort in Sorting algorithms folder.

added python program for quick sort

---

Dynamic Programming/Klee's Algorithm.cpp

I have added the C++ code for Klee's Algorithm 
fixes #203

Klee's Algorithm added

---

Data Structures/Trees/Diameter_Binary_Tree.cpp

I have added the C++ code for Diameter of the Binary Tree 

Diameter of Binary Tree added

---

Bit Manipulation/Bit_Difference.cpp
Bit Manipulation/Count_total_set_bits.cpp
Bit Manipulation/Find_position_of_set_bit.cpp
Bit Manipulation/Non_Repeating_Numbers.cpp
Bit Manipulation/Number_of_1_Bits.cpp
Bit Manipulation/Power_of_2.cpp

@smv1999  I have added Bit manipulation C++ programs for  Isuue No #221

Added 6 programs in Bit Manipulation directory #221

---

General Questions/Round-Robin-Algorithm.c

Round-Robin-algorithm-added

---

DSA 450 GFG/max_sum.py
DSA 450 GFG/max_sum_bottom_up.py
DSA 450 GFG/max_sum_memoization.py

Python solution for max sum in DSA450

---

Data Structures/Graphs/Center_Of_Star_Graph.cpp

I have added the C++ code for center of a Star Graph 
fixes #226

Center of star graph added

---

Dynamic Programming/ClimbingStairs_bottom_up.py
Dynamic Programming/ClimbingStairs_memoization.py

Python solution for Climbing stairs DP - Memoization , bottom up approach

---

Data Structures/Graphs/RottenOranges.cpp

Given a grid of dimension nxm where each cell in the grid can have values 0, 1 or 2 which has the following meaning:
0 : Empty cell
1 : Cells have fresh oranges
2 : Cells have rotten oranges
We have to determine what is the minimum time required to rot all oranges. A rotten orange at index [i,j] can rot other fresh orange at indexes [i-1,j], [i+1,j], [i,j-1], [i,j+1] (up, down, left and right) in unit time. 
Example 1:
Input: grid = {{0,1,2},{0,1,2},{2,1,1}}
Output: 1
Explanation: The grid is-
0 1 2
0 1 2
2 1 1
Oranges at positions (0,2), (1,2), (2,0)
will rot oranges at (0,1), (1,1), (2,2) and 
(2,1) in unit time.
Example 2:
Input: grid = {{2,2,0,1}}
Output: -1
Explanation: The grid is-
2 2 0 1
Oranges at (0,0) and (0,1) can't rot orange at
(0,3).

Rotten Oranges 

---

Graph/Khan_algo.py

Khan's algorithm is based on the topological sort

Topological sort

---

Data Structures/Linked Lists/Detet_Cycle_In_LinkedList.cpp

I have added the C++ code to Detect Cycle In Linked List
fixes #235

Detect Cycle In Linked List

---

Data Structures/Graphs/WordBoggle.cpp
Data Structures/Trees/Construct_Binary_Tree_from_Preorder_and_Inorder_Traversal.cpp

Given a dictionary of distinct words and an M x N board where every cell has one character. Find all possible words from the dictionary that can be formed by a sequence of adjacent characters on the board. We can move to any of 8 adjacent characters, but a word should not have multiple instances of the same cell.
Example 1:
Input: 
N = 1
dictionary = {"CAT"}
R = 3, C = 3
board = {{C,A,P},{A,N,D},{T,I,E}}
Output:
CAT
Explanation: 
C A P
A N D
T I E
Words we got is denoted using same color.
Example 2:
Input:
N = 4
dictionary = {"GEEKS","FOR","QUIZ","GO"}
R = 3, C = 3 
board = {{G,I,Z},{U,E,K},{Q,S,E}}
Output:
GEEKS QUIZ
Explanation: 
G I Z
U E K
Q S E 
Words we got is denoted using same color.
-----------------------------------------------------------------------------
Companies
Amazon …

WordBoggle.cpp

---

Sorting Algorithms/Bucket Sort.py

Solved bucket sort in python.
Fixed issue #245

Solved Bucket Sort

---

Data Structures/Graphs/Topological_Sort.cpp

I have added the C++ code for Topological Sort
fixes #244

Topological Sort added

---

Sorting Algorithms/bucket_sort.cpp

I have added the C++ code for bucket sort algorithm 
fixes #245

Bucket Sort added

---

Dynamic Programming/MirrorOfBinTree.py

Mirror of BT in DSA450 - Python solution

---

Dynamic Programming/binomial_coefficient.cpp

Added Binomial Coefficient problem in C++ for DP section .

Binomial Coefficient in C++ using DP  fixes #222

---

Data Structures/Linked Lists/Singly Linked List/Flattening_a_link_list.cpp

Given a Linked List of size N, where every node represents a sub-linked-list and contains two pointers:
(i) a next pointer to the next node,
(ii) a bottom pointer to a linked list where this node is head.
Each of the sub-linked-list is in sorted order.
Flatten the Link List such that all the nodes appear in a single level while maintaining the sorted order. 
Note: The flattened list will be printed using the bottom pointer instead of next pointer.
Example 1:
Input:
5 -> 10 -> 19 -> 28
|     |     |     | 
7     20    22   35
|           |     | 
8          50    40
|                 | 
30               45
Output:  5-> 7-> 8- > 10 -> 19-> 20->
22-> 28-> 30-> 35-> 40-> 45-> 50.
Explanation:
The resultant linked lists has every 
node in a single level.
(Note: | represents the bottom …

Flattening a Linked List 

---

DSA 450 GFG/rotate_by_90.py

Python solution for rotate matrix by 90 in anticlockwise

---

Data Structures/Stacks/Largest_rectangle_area_under_histogram.cpp

I have added the C++ code for the above program 
fixes #260

Largest rectangle area under histogram added

---

Data Structures/Stacks/Sort_stack_using_recursion.cpp

I have added the C++ code for sort the stack using recursion 
Please review my code 
fixes #259

Sort stack using recursion added

---

General Questions/Difficult_pattern.c
General Questions/Difficult_pattern2.c
General Questions/Difficult_pattern3.c
General Questions/Difficult_pattern4.c

Added some difficult pattern printing programs asked in interviews.
Resolves issue #250

Add more problems in General Questions

---

Arrays/sum_of_three_values.c++

Add Sum of three values 

---

DSA 450 GFG/subtree_of_another_tree.py

Python solution for subtree of another tree

---

Dynamic Programming/Collinearity_of_three_points.cpp

I have added the C++ code for collinearity of three points
fixes #271

Collinearity of three points added

---

Dynamic Programming/Longest_common_substring.cpp

Added Longest Common Substring program (in cpp)

---

Sorting Algorithms/bubble_sort.py

Added bubble sort in python.

---

Arrays/Minimize_the_height.cpp

Minimize the maximum difference between heights

---

Sorting Algorithms/wavesort.cpp

WaveSort Question is added to the Sorting Algorithms Folder

---

Strings/findAndReplacePattern.cpp

Added [Find and Replace Pattern](https://leetcode.com/problems/find-and-replace-pattern/) of Leetcode(Medium)
Fixes #312

Added Find and Replace Pattern

---

Numbers/armstrong_number.cpp

feat: Add Armstrong Number

---

Backtracking/Graph_Coloring_Problem.cpp

Added Graph coloring problem code i.e. to determine all the different ways in which graph can be colored using at most m colors.
- Graph is represented by its adjacency matrix.
- Colors are represented by the integers 1,2,...,m.
- I have used C++ language for this problem.
Issue number of this problem is #293

Added Graph Coloring Problem code in Backtracking folder

---

Backtracking/tic_tac_toe_game.py

Yes
Tic Tac Toe game in python using backtracking.
#242

Tic Tac Toe Game

---

README.md
Searching Algorithms/linear_search.py

Added linear search in python 
#313 

Added linear search in python

---

Backtracking/water_jug_problem.py

Yes
Water Jug Problem solved in python using backtracking.
#292

Water Jug Problem

---

Arrays/ShuffleTheArray.cpp

Added ShuffleTheArray

---

Data Structures/Linked Lists/Remove_all_Duplicates_from_Linnkedlist.cpp

I have added the C++ code 
fixes #287

Remove all Duplicates from Linkedlist added

---

Searching Algorithms/binary_search.cpp

Yes
Added binary search in cpp.
#303 

Added binary search in cpp.

---

Data Structures/Linked Lists/Singly Linked List/simple_linkedlist_operations.cpp

Yes
I added the program for simple linked list operations like insertion, deletion, searching, and modifying.
assigned issue #416

Simple Linked List Operations in C++

---

Data Structures/Linked Lists/Singly Linked List/Single-linked-list-operations.py

Yes
I have added a python program for singly linked list with all operations like inserting deleting from beginning, end at any given index, etc
Closes : #397

Python-singly-linked-list-all-operations

---

Data Structures/Stacks/BalancedParenthesis.java

Balanced Parenthesis

---

Standard Template Library/balancedparenthesis_stl.cpp

Added the stl approach for solving the balanced parenthesis problem

---

Data Structures/Graphs/WarshallAlgorithm.py

Fixes #363 
Yes
Added the warshall algorithm code in python
#363 

Warshall Algorithm in Python 

---

Backtracking/Hamiltonian_Cycle.py

Yes
Hamiltonian Cycle using backtracking in python.
#409

Hamiltonian Cycle (Python)

---

Searching Algorithms/binary_search.py

Added binary search in python using an iterative approach
Yes
Implemented the binary search algorithm in python. Proper guidelines were followed on every step. Good comments are added to the code to help readers understand the implementation.
#456 

Added binary search in python

---

Strings/KMP_Algorithm.cpp
Strings/Rabin_Karp_Algorithm.cpp

Yes
I have added the programs for Rabin_Karp and KMP Algorithm in Strings Folder.
I am contributing as a part of DCP21.
I was assigned the issue (#225) for the same.

Added Rabin_Karp and KMP Algorithm Programs in Strings Folder 

---

README.md
Recursion/first_index_of_element_in_array.cpp

Yes
Added first index of an element in array
#454 

Added first index of an element in array

---

Arrays/Kth_smallest_element_in_an_array_using_heap.cpp

It can be made simple by using a heap which reduces the time complexity from the brute force approach O(n^2) to O(n).

Kth smallest element in an array

---

Arrays/Max_XOR_of_Two_Array.cpp

I have added  the C++ code for Max XOR of Two Array
fixes : #347

Max XOR of Two Array added

---

Data Structures/Trees/expression_tree_evaluation.py

Added expression_tree_evaluation.py file which contains code in python for the same.
Yes
Created code for evaluating expression trees which are very important. It defines a class Node to store the node of tree (value and children pointers) and a function which recursively traverses the tree while evaluating. All guidelines were followed. Good comments are added to the file for readers.
closes issue #463 

expression_tree_evaluation in python

---

Dynamic Programming/Buy_And_Sell_Stocks.cpp

Buy and sell the stock with maximum profit.
We have given stock prices on n days, what is the total maximum profit we can get
sample input :
9 11 6 7 19 4 1 6 18 4 
sample output: 17

buy and sell stock with maximum profit

---

Data Structures/Trees/Flatten_BinaryTree_to_LinkedList.cpp

Issue [#350](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/350) solved.
Solved the flatten binary tree to linked list problem of Leetcode using C++.

Flatten Binary Tree to Linked List using CPP

---

DSA 450 GFG/mirror_tree.py

Python solution for mirror tree

---

Data Structures/Stacks/infix_to_postfix_conversion.py

Yes
Added python code to convert infix expression to postfix using stacks and manually tested the same. I have followed all the guidelines during the process.
closes #485  
Please merge my PR under Devincept21 and review as soon as possible.

Added python file for infix to postfix

---

Recursion/All_indices_of_element.cpp

Yes
Added all indices of an element in an array. 
#413 

Added all indices of an element in array.

---

Backtracking/Graph_Coloring_Problem.py

Yes
Graph Coloring Problem solved using backtracking.
#494 

Graph Coloring Problem

---

Data Structures/Linked Lists/Singly Linked List/Intersection_Of_Two_LinkedList.cpp

Issue #351 solved.
Intersection of 2 linked-list program in C++. It contains required descriptions.

Intersection of two Linked-List in CPP

---

Backtracking/Backtracking-Rat in a Maze.cpp

Yes
Solve Backtracking Rat in a Maze in cpp.
fixes #419 

Backtracking Rat in a Maze

---

Strings/Validate_IP_address.cpp

Yes
It's a code to check whether the IP address is correct or not.
linked issue#523

Validating IP addresses

---

Dynamic Programming/Unbounded_Knapsack.cpp

Yes
Solved issue :  #441
Unbounded Knapsack (Knapsack with Duplicate Items) in C++ 

Unbounded Knapsack in C++ #441

---

General Questions/Josepheus_problem.cpp

Yes
Added Josepheus Problem in C++ language in general Question folder
Issue Number - #391 

Added Josepheus Problem fixes #391

---

Arrays/Minimum_XOR_Value.cpp

I have added the C++ code for this 
fixes #348

Minimum XOR Value added

---

Backtracking/Knight's_Tour.py

Yes
I've solved this problem using backtracking in python.
#526 

Knight's Tour

---

Backtracking/Cryptarithmetic_Problem.py

Yes
Cryptarithmetic Problem Solving using backtracking.
#407

Cryptarithmetic Problem Solving (Python)

---

Backtracking/Sudoku.py

Yes
I used backtracking for creating the game in python.
#532 

Sudoku (Python)

---

Arrays/containerWithMostWater.cpp

YES
Added containerWithMostWater.cpp in array directory
#336 

Added containerWithMostWater.cpp

---

Arrays/searchInRotatedSortedArray.cpp

YES
Added searchInRotatedSortedArray.cpp in Array directory
#344

Added searchInRotatedSortedArray.cpp

---

Arrays/Median_of_two_Sorted_arrays_of_different_size.cpp

I have added the C++ code .
fixes #544

Median of two Sorted arrays of different size added

---

Sorting Algorithms/shell_sort.py

YES
The changes contains adding of new program which is the implementation of shell sort in python
Shell Sort in Python #510

Implementation of Shell Sort in Python

---

Backtracking/Subset_Sum.py

Yes
Solved subset sum problem using backtracking in python.
#562 

Subset Sum

---

Data Structures/Linked Lists/Singly Linked List/Reverse_Nodes_in_K_Groups.cpp

Issue #352 solved.
Problem reverse nodes in k groups coded using C++ with required comments.

Reverse Nodes in k-Groups using CPP

---

DSA 450 GFG/Union_Arrays.cpp

Count Union of two arrays

---

Data Structures/Trees/segment_tree_range_sum_and_update_query.py

Yes
Added segment tree code in python for creation, sum range query and update query. Have checked the code and all guidelines are followed.
Also good project and theory explanation, along with well commented code with an example are added to the file.
closes #554 

Segment Tree

---

Backtracking/graph_coloring.c

Added Graph Coloring Problem in C

---

Searching Algorithms/8_Puzzle_Problem_using_A_star_Algorithm.py

Yes
Used a search algorithm in AI to solve the problem in python.
#579 

8 Puzzle Problem using A* Algorithm

---

Arrays/Fair Playoff.cpp

Yes
I have added the solution to the Fair Playoff Codeforces question in the Arrays Folder.
- [✅] I've read the contribution guidelines.
- [✅] I've checked the issue list before deciding what to submit.
#541

Add Fair Playoff Codeforces Solution

---

OOPs/Inheritance/Single_Inheritance_cpp.cpp

@Saviour1001 and @smv1999 please review the pull request.
Yes.
I have added code for Single Inheritance in C++. 
This is a solution to [Issue-321](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/321).

Added the code for Single Inheritance in C++

---

DSA 450 GFG/TowerOfHanoi.cpp

Yes
Solve Tower of Hanoi using C++.
fixes #361 

Tower of Hanoi

---

Data Structures/Trees/Maximum_Element_of_Binary_Tree.cpp

I have provided the C++ code 
Please review my code 
fixes #552

Maximum Element of Binary Tree added

---

Dynamic Programming/Knapsack_greedyMethod.c

Added Knapsack Problem in C

---

Dynamic Programming/Coin_Change.cpp

YES
Dynamic programming Fixes : #507
Coin change (Total no of ways ) in C++

Coin change(DP) in C++

---

Searching Algorithms/8_Puzzle_Problem_using_BFS.py

Yes
Used a search algorithm in AI to solve the problem in python.
#584 

8 Puzzle Problem using BFS

---

OOPs/Inheritance/Multiple_Inheritance_cpp.cpp

@Saviour1001 and @smv1999 please review the pull request.
Yes.
I have added the code for Multiple Inheritance in C++.
This Pull Request is a solution to [issue-322.](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/322)

Added the code for Multiple Inheritance in C++

---

Arrays/Average_Calculator.py

Yes
Average calculator using python.
#594 

Average Calculator

---

Strings/Bad_String.py

Yes
Explored 'try and except' functionality in python.
#596 

Bad String

---

Dynamic Programming/Square_brackets.cpp

Yes I have read the contributing guidelines
This is the solution to the SPOJ problem [SQRBR](https://www.spoj.com/problems/SQRBR/) coded in C++.
Solves issue #546 

Added SQRBR problem

---

OOPs/Inheritance/Hierarchical_Inheritance_cpp.cpp

Yes
I have added the code for Hierarchical Inheritance in C++.
This Pull Request is a solution to [issue-323](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/323).

Added the code for Hierarchical Inheritance in C++

---

Strings/check_if_strings_are_rotation_of_eachother.cpp

Yes
Checking if string one is  rotation of another string. 
Linked Issues #572 

String Rotation

---

Dynamic Programming/job_sequencing_greedyMethod.c

Added Job Sequencing Problem in C

---

OOPs/Inheritance/Multilevel_Inheritance_cpp.cpp

Yes
I have added the code for Multilevel Inheritance in C++.
This Pull Request is a solution to [issue-325](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/325).

Added the code for Multilevel Inheritance in C++

---

Data Structures/Linked Lists/Singly Linked List/Delete_node_without_head_pointer.cpp

Yes
I want to write a code for deleting a node without the help of a head node but with the help of a pointer at the node that needs to be deleted.
Issue#612

Deleting a node without a head pointer

---

Data Structures/Stacks/maximum_size_of_balanced_bracket_sequence.cpp

I have added the C++ code 
fixes #577

maximum size of balanced bracket sequence added

---

2D Arrays/sort_matrix_diagonally.py

Added matrix files

---

DSA 450 GFG/AllocateMinimumNumberOfPages.cpp

Yes
I have added a CPP  solution for Added the Allocate Minimum No. of Pages (Issue No : #307 ) .
My code is well documented and contains complete explanation of the program with well written comments and sample test cases.
Issue No : #307 

Added the Allocate Minimum No. of Pages.cpp

---

Arrays/Binary_Numbers.py

Yes
Binary Numbers problem solved in python.
#626 

Binary Numbers 

---

Bit Manipulation/Bitwise_AND.py

Yes
Bitwise AND problem solved in python.
#628 

Bitwise AND 

---

Arrays/findMinimumInRotatedSortedArray.cpp

YES
Added findMinimumInRotatedSortedArray.cpp in strings/ directory
#345

Added findMinimumInRotatedSortedArray.cpp

---

Recursion/subsets.cpp
Recursion/subsets2.cpp

Yes
Added the recursive solution in C++ to the problems of the subset and duplicate subset of LeetCode under the recursion directory
This solves #632

Added Recursive solution to subset problem

---

OOPs/Inheritance/Hybrid_Inheritance_cpp.cpp

Yes
I have added the code for Hybrid Inheritance in C++.
This Pull Request is a solution to [issue-326](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/326).

Added the code for Hybrid Inheritance in C++

---

2D Arrays/matrices.java

Operations on matrices .

---

Data Structures/Stacks/Previous_Greater_Element.cpp

I have added the C++ code 
Please review 
fixes #615

Previous Greater Element added

---

Data Structures/Trees/BinaryTree_Maximum_Path_Sum.cpp

Issue #353 solved.
Problem binary tree maximum path sum coded using C++.

Binary Tree Maximum Path Sum using CPP

---

Backtracking/combinational_sum.py
General Questions/combinational_sum.py

added combinational sum

---

Data Structures/Graphs/BFS.py
Data Structures/Graphs/DFS.PY

YES
Implementation of BFS and DFS in python
Graph traversal BFS and DFS  #513

Graph traversal BFS and DFS in Python

---

Data Structures/Trees/lowest_common_ancestor_binary_tree.py

Yes
Added python code to find LCA in a binary tree in Python. Have checked the code and all guidelines are followed.
Also good project and theory explanation, along with well commented code with an example are added to the file.
closes #634 

LCA in Binary tree in Python

---

Dynamic Programming/Floyed- Warshall.c

Added Floyed- Warshall Algorithm in C

---

SilverAndGold.java

This Closes #575  
Problem statement:
There are N coins kept in a line. Each coin has two sides - one is colored gold and the other silver. You can flip two adjacent coins any number of times. You need to make the gold-colored side of every coin facing up. You are given the initial status of coins in a binary string s where 1 represents the gold side facing up and 0 represents the silver side facing up. If it is possible to make the gold-colored side of every coin facing up, return  Yes, otherwise return  No
Input:
N = 8, s = "11001100"
Output:
Yes
Explanation:
Flipping 3rd and 4th coin together and 7th
and 8th coin together will do the task.

Added Silver and Gold Problem Solution in Java

---

Bit Manipulation/rotate_bits.cpp

A rotation (or circular shift) is an operation similar to shift except that the
bits that fall off at one end are put back to the other end. 
In left rotation, the bits that fall off at left end are put back at right end. 
In right rotation, the bits that fall off at right end are put back at left end.
I have added the C++ code 
Please review my code 
fixes #654

Rotate Bits added 

---

Dynamic Programming/ZigZag Conversion_leetcode.java
Dynamic Programming/zigzag_conversion.java

Add Zig Zag Conversion

---

Codechef Problems/DSA Learning Series/Alternative Square Pattern.java
Codechef Problems/DSA Learning Series/Buy Please.c
Codechef Problems/DSA Learning Series/Factors Finding.c
Codechef Problems/DSA Learning Series/Find Second Largest.c
Codechef Problems/DSA Learning Series/Find me.c
Codechef Problems/DSA Learning Series/Is both or not.c
Codechef Problems/DSA Learning Series/Raju and his trip.c
Codechef Problems/DSA Learning Series/Range odd.c
Codechef Problems/DSA Learning Series/Reverse Star Pattern.c
Codechef Problems/DSA Learning Series/Reverse me.c
Codechef Problems/DSA Learning Series/Valid traingle or not.c
Codechef Problems/Richie Rich.c

Codechef Dsa series solutions added

---

General Questions/Sorted-array-to-BST.py

Yes
Sorted-array-to-BST python program added 
Closes : #550 

Sorted-array-to-BST program added

---

Data Structures/Trees/path_to_node_binary_tree.py

Yes
Added python code to find path to a node from root node in a binary tree in Python. Have checked the code and all guidelines are followed.
Also good project and theory explanation, along with well commented code with an example are added to the file.
closes #656 

Path to node in Binary tree 

---

Data Structures/Trees/binary_tree_right_side_view.py

YES
For a given binary tree returning the values of nodes that are appearing on the right side view from top to bottom
- [yes ] I've read the contribution guidelines.
- [yes] I've checked the issue list before deciding what to submit.
Binary Tree Right Side View #667

Binary Tree right side view

---

General Questions/Common_elements_in_all_rows_of_a_given_matrix.cpp

Yes
Writing the code in c++ for checking all the common elements in all he rows of the matrix.
Issue#673

Checking the common elements in all the rows of a matrix

---

Data Structures/Linked Lists/Singly Linked List/oddEvenLinkedList.cpp

YES
Added oddEvenLinkedList.cpp in Data Structures/Linked Lists/Singly Linked List/
#346 

Added oddEvenLinkedList.cpp

---

Strings/zigZagConversion.cpp

YES
Added zigZagConversion.cpp in strings/ directory
fixes #646 

Added zigZagConversion.cpp

---

Backtracking/N-Queen Problem.cpp

YES.
Solve N-Queen Problem using C++
fixes #619 

N-Queen Problem using C++

---

Backtracking/Knight's_Tour.java

Yes
Added knight tour's problem added under backtracking folder.
Fixes #366

knight tour's problem added

---

Techgig Code Gladiators 2021/semifinals/JazzyAndCricketBalls.cpp

YES
Issue solved : #686 
Semifinal round question
jazzy and cricket balls using C++(Techgig Code Gladiators 2021)

Jazzy and Cricket Balls using C++

---

General Questions/Longest_Common_Prefix.py

YES
Implementation of python program to find the longest common prefix amongst the given list of strings. If there is no common prefix then returning 0.
Longest-Common-Prefix #657

Implementation of LongestCommonPrefix in Python

---

Arrays/Missing_integer.cpp
General Questions/AP_GP.cpp

Arithmetic , Geometric progression .

---

Strings/Longest_Substring_Without_Repeating_Characters.cpp

YES
Longest Substring Without Repeating Characters
- [yes ] I've read the contribution guidelines.
- [yes ] I've checked the issue list before deciding what to submit.
Longest Substring Without Repeating Characters in C++ #691

Longest Substring Without Repeating Characters

---

Data Structures/Trees/BST_Level_Order_Traversal.py

Yes
Program for BST Level Order Traversal in python.
#706 

BST Level Order Traversal

---

Data Structures/Trees/AVL_Tree_or_not.cpp

I have added the C++ code to check if the given BST is an AVL tree or not.
AVL Tree can be defined as height balanced binary search tree in which each node is associated with a balance factor
which is calculated by subtracting the height of its right sub-tree from that of its left sub-tree.
Please review my code 
fixes #708

AVL Tree added

---

Arrays/TwoSum.cpp

Created TwoNum

---

Recursion/Last_index_of_element_in_array.cpp

Yes
Added last index of an element in an array.
#553 

Added last index of a number in array

---

DSA 450 GFG/LongestPalindromicSubstring.py

Yes
Link to the problem : https://leetcode.com/problems/longest-palindromic-substring/
Closes #702 
Closes #702 

Python solution for Longest palindromic substring

---

DSA 450 GFG/merge_without_extra_space.cpp

yes
Added a c++ solution for Merge Without Using Extra Space 
#695 

Added merge_without_extra_space

---

Dynamic Programming/Matrix_chain_multiplication.c

Matrix Chain Multiplication in C

---

Data Structures/Stacks/balanced_parentheses.py

YES
Given a string s containing just the characters '(', ')', '{', '}', '[' and ']', determine if the input string is valid.
An input string is valid if:
1. Open brackets must be closed by the same type of brackets.
2. Open brackets must be closed in the correct order.
- [yes] I've read the contribution guidelines.
- [yes ] I've checked the issue list before deciding what to submit.
Check for balanced parenthesis in Python #722

Python code to Check for balanced parentheses in an expression

---

Data Structures/Trie/Implement_trie.cpp

Issue #291 Implement Trie data structure

---

Arrays/Strassen's_Algo.c

(https://github.com/smv1999/CompetitiveProgrammingQuestionBank/blob/master/CONTRIBUTING.md)?
YES
Strassen's Algorithm for Matrix Multiplication in C Language
Closes: #710 

Strassen's Algo Matrix Multiplication in C

---

Hackerrank solutions/the_minion_game.py

Yes
Kevin and Stuart want to play the 'The Minion Game'.
Game Rules
1. Both players are given the same string S .
2. Both players have to make substrings using the letters of the string S.
3. Stuart has to make words starting with consonants.
4. Kevin has to make words starting with vowels.
5. The game ends when both players have made all possible substrings.
Scoring
A player gets +1 point for each occurrence of the substring in the string S.
- [Yes ] I've read the contribution guidelines.
- [Yes ] I've checked the issue list before deciding what to submit.
The Minion Game | HackerRank #724

The minion game , Hacker Rank

---

Sorting Algorithms/SelectionSort.js

I have added the program for selection sort in javascript
fixes #720 
SELECTION SORT: 
* inplace comparison-based sorting algorithm.
* list is divided into two parts, the sorted part at the left end and the unsorted part at the right end. 
* The smallest element from the unsorted array is found and swapped with the leftmost element.
ie, added to the sorted array. 
* This process continues moving unsorted array boundary by one element to the right.

Selection Sort added

---

Strings/Capitalizing.py

Yes
The aim was to replace the first character of all the words with their upper case characters.
#746 

Capitalizing

---

Arrays/Divisor_Sum.py

Yes
The aim was to calculate the sum of all the divisors of the entered number and display it.
#748 

Divisor Sum

---

Data Structures/Stacks/merge_intervals.cpp

yes.
Added Merge Intervals Problem to Data Structures/ Stack section.
Issue No. #763

Added Merge_intervals fixes #763

---

Arrays/Median_of_two_sorted_array.java

Yes
Added solution of Median Of Two Sorted Arrays In Java.
#499 

Added Solution of Median of Two Sorted Array(Letcode) in Java.

---

Data Structures/Trees/Height_of_BST.py

Yes
Built the program in python.
#769 

Height of a BST 

---

Arrays/Hourglass_Sum.py

Yes
Program made in python.
#771 

Hourglass Sum 

---

OOPs/Inheritance/Hybrid_Inheritance _cpp.cpp

Yes
I have added the Code for Hybrid Inheritance in C++
Solution to [issue-326](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/326)

Code for Hybrid Inheritance in C++

---

OOPs/Inheritance/Hybrid_Inheritance _cpp.cpp
OOPs/Inheritance/Protected_Inheritance_cpp.cpp
OOPs/Inheritance/Public_Inheritance_cpp.cpp

Yes
I have added the Code for Protected Inheritance in C++
Solution to [issue-328](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/328)

Added the code for Protected Inheritance in C++

---

OOPs/Inheritance/Hybrid_Inheritance _cpp.cpp
OOPs/Inheritance/Public_Inheritance_cpp.cpp

Yes
I have added the Code for Public Inheritance in C++
Solution to [issue-327](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/327)

Added the code for Public Inheritance in C++

---

Strings/ConvertToPalindrome_Strings.cpp

Yes
This is a solution of the problem "Convert to Palindrome" of Strings.
Fixes #751 

ConvertToPalindrome(String) added in the Strings

---

Data Structures/Graphs/Boruvka_algorithm_for_finding_MST.cpp

Boruvka’s Algorithm is a greedy algorithm used for finding Minimum Spanning Tree (MST) for
a connected, weighted, and undirected graph.
The goal of the algorithm is to connect “components” using the shortest or cheapest edge between
the components. It begins with all of the vertices considered as separate components.
I have added the C++ code for this. 
fixes #765

Boruvka algorithm for finding MST added

---

Arrays/Leap_Year.py

Yes
Leap year checker in python.
#788 

Leap Year Checker

---

Data Structures/Trees/top_view_binary_tree.cpp

Given a binary tree, print the nodes in left to right manner as visible from above the tree.
Input is given in order of root left child then right child.
I have added the C++ code for top view of a binary tree 
fixes #745

top view binary tree added

---

Codechef Problems/Food_Chain.c

yes
Solution to codechef's FOOD CHAIN PROBLEM in C language 
#796 

Solution to codechef's FOOD CHAIN PROBLEM

---

Arrays/Maximum_Difference.py

Yes
Maximum difference program in python.
#790 

Maximum Difference

---

Strings/alternating_characters.c

YES
Given a string containing characters A and B only. The task is to change it into a string such that there are no matching adjacent characters. To do this, you are allowed to delete zero or more characters in the string. Find the minimum number of required deletions.
EXAMPLE: s =AABAAB
SOLUTION: Remove an A at positions 0 and 3 to make s= ABAB in 2 deletions.
Closes #753

alternating_characters file added

---

Data Structures/Trees/normal_tree.py

Yes
Added code that builds a simple tree data structure and do some operation
Constructing tree data structure using python
Issue: #756 

Added normal tree using python

---

OOPs/Constructor/Default_Constructor_cpp.cpp

Yes
Added the code for Default Constructor in C++
Solution to [issue-793
](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/793)

Added the code for Default Constructor in C++

---

OOPs/Constructor/Default_Constructor_cpp.cpp
OOPs/Constructor/Parameterized_Constructor_cpp.cpp

Yes
Added the code for Parameterized Constructor in C++
Solution to [issue-794
](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/794)

Added the code for Parameterized Constructor in C++

---

Arrays/Min_Max_Sum.py

Yes
Min Max Sum program in python.
#802 

Min Max Sum

---

Data Structures/Stacks/Palindrome_Checker.py

Yes
Palindrome checker in python.
#811 

Palindrome Checker

---

Data Structures/Graphs/Adjacency_List.cpp

I have added the C++ code for ADJACENCY LIST FOR REPRESENTING DIRECTED GRAPH
It is a method of representing a digraph using 2 linked lists
1. Node list
2. Edge list corresponding to each node
Edges arising from a node are stored in edge list of each node
fixes #814

Adjacency List added

---

Data Structures/Linked Lists/Singly Linked List/compare_two_linkedlist.py

Yes
Added a code that compares two linked lists if the value in both LinkedList is the same it returns "Same" else returns "Not same"
Compare two linked lists with python
Issue: #787

Compare two linked lists with python

---

Strings/Longest_Substring_with_AtLeast_K_Repeating_Characters.cpp

Yes
To find Longest Substring with At Least K Repeating Characters
- [ Yes] I've read the contribution guidelines.
- [ Yes] I've checked the issue list before deciding what to submit.
Longest Substring with At Least K Repeating Characters in C++ #826

Longest Substring with At Least K Repeating Characters 

---

Sorting Algorithms/Bubble_Sort.java

Bubble_Sort implementation in java.
Yes
Bubble_Sort implimentation in java.
Bubble_Sort implimentation in java.
Issue: #786

Add Bubble_Sort.java

---

Recursion/remove_duplicates.cpp

Yes
Added remove duplicates in cpp in recursion folder.
#728 

Added remove duplicates

---

DSA 450 GFG/next_greater_element.py

Python solution for Next greater element in DSA450

---

Data Structures/Stacks/Maximum_size_rectangle_binary_sub-matrix.cpp

Yes, I have.
- Link to the problem: https://www.geeksforgeeks.org/maximum-size-rectangle-binary-sub-matrix-1s/
- Given a binary matrix, find the maximum size rectangle binary-sub-matrix with all 1’s. 
Example: 
Input:
0 1 1 0
1 1 1 1
1 1 1 1
1 1 0 0
Output :
1 1 1 1
1 1 1 1
Explanation : 
The largest rectangle with only 1's is from 
(1, 0) to (2, 3) which is
1 1 1 1
1 1 1 1 
Fixes issue no. #775 

Maximum size rectangle binary sub-matrix with all 1s

---

OOPs/Constructor/Constructor_Overloading_cpp.cpp

Yes
Added the code for Constructor Overloading
Solution to #831

Added the code for Constructor Overloading

---

OOPs/Constructor/Copy_Constructor_cpp.cpp

Yes
Added the code for Copy Constructor
Solution to #832

Added the code for Copy Constructor

---

OOPs/Constructor/Deep_Copy_Constructor_cpp.cpp

Yes
Added the code for Deep Copy Constructor in C++
Solution to #844

Added the code for Deep Copy Constructor in C++

---

OOPs/Constructor/Shallow_Copy_Constructor_cpp.cpp

Yes
Added the code for Shallow Copy Constructor in C++
Solution to #845 

Added the code for Shallow Copy Constructor in C++

---

Codechef Problems/Red_alert.c

Yes
Solution to codechef problem-july lunchtime contest in C language
#851 

Red alert solution (codechef problem) in C language.

---

Codechef Problems/FlappyBird.java

YES.
This issue is from CodeChef Starters June 2021.
I wish to work on this issue in Java language.
Problem statement
https://www.codechef.com/START5C/problems/FLAPPYBD/
Fixes issue no. #855  

Added Flappy bird problem

---

Hackerrank solutions/30 days Of Code/Day8-Dictionaries_and_Maps.c

Yes
Added Day 8 Solution to hackerrank-30 days of code folder
The question is based on : 
Key-Value pair mappings using a Map or Dictionary data structure
#858 

Added Day 8 Solution to hackerrank-30 days of code folder

---

OOPs/Encapsulation/Encapsulation_cpp.cpp

Yes
Added the code for Encapsulation in C++
Solution to [issue-864](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/864)

Added the code for Encapsulation in C++

---

OOPs/Abstraction/Abstraction_cpp.cpp

Yes
Added the code for Abstraction in C++
Solution to [issue-863](https://github.com/smv1999/CompetitiveProgrammingQuestionBank/issues/863)

Added the code for Abstraction in C++

---

General Questions/possible no from word.cpp

Yes
#861 
The program to convert number in word format 

Added code for the program to convert given no to word in general question

---

Data Structures/Linked Lists/Singly Linked List/merge_two_sorted_linkedlist.py

Yes
Added a code that merges two sorted linked list into the single linked list using python
Merge two sorted linked list using python
Issue: #836

Added a code to merge linkedlist using python

---

Sorting Algorithms/heap_sort.py

HEAP SORT
It is a sorting technique based on the heap data structure.
Heap is a complete binary tree, in which every level except the last, is filled
completely with its nodes, and nodes are far left.
We implement this sorting in an array using Max Heap, in which the parent node 
value is greater than it child node values. 
fixes #835

Heap Sort added

---

Codechef Problems/TheLeadGame.cpp

Created TheLeadGame

---

OOPs/Inheritance/MultiLevel_Inheritance.java

yes
Added MultiLevel Inheritance in java
#341 issue
I have done a pull request with 3 issues in it (#736 pull request) before 

Added MultiLevel Inheritance in Java

---

OOPs/Inheritance/HierarchicalInheritance.java

yes
Added Hierarchical Inheritance in java
#343 issue
I have done a pull request with 3 issues in it (#736 pull request) before.Due to my exams, there was a delay 

Added Hierarchical Inheritance in java

---

OOPs/Polymorphism/Method_Overloading.java

yes
Added Method overloading in java
#340 issue
I have done a pull request with 3 issues in it (#736 pull request) before. Due to my exams, there was a delay

Added Method overloading in java

---

OOPs/Polymorphism/Method_Overriding.java

yes
Added Method overriding in java
#804 

Added Method overriding in java

---

Sorting Algorithms/InsertionSort.java

yes
Added Insertion Sort in java
#885 

Added Insertion Sort in java

---

OOPs/Destructor/Destructor_cpp.cpp

Yes
Added the code for Destructor in C++
Solution to #888

Added the code for Destructor in C++

---

OOPs/Friend Class & Function/Friend_Class_cpp.cpp

Yes
Added the code for Friend Class in C++
Solution to #890

Added the code for Friend Class in C++

---

General Questions/Polynomial_Verification.py

Yes
Aim: Given a polynomial P of a single indeterminate (or variable), x. Also, given the values of x and k. The task is to verify if P(x) = k.
Language to be Used: Python
#902 

Polynomial Verification

---

Numbers/Prime_Numbers.py

Yes
Aim: To check if the entered numbers are prime or not.
Language to be Used: Python
#904 

Prime Numbers

---

Data Structures/Graphs/BFS.py
Data Structures/Stacks/Previous_Greater_Element.cpp
Dynamic Programming/Buy_And_Sell_Stocks.cpp
Dynamic Programming/Square_brackets.cpp
Dynamic Programming/knapsack_01.cpp
General Questions/intersection_of_arrays.c
Numbers/Sieve-of-Eratosthenes.cpp
Sorting Algorithms/insertion_sort.cpp
Strings/Capitalizing.py
Trie/Trie_add_Search_using_dict.py

There are small typos in:
- Data Structures/Graphs/BFS.py
- Data Structures/Stacks/Previous_Greater_Element.cpp
- Dynamic Programming/Buy_And_Sell_Stocks.cpp
- Dynamic Programming/Square_brackets.cpp
- Dynamic Programming/knapsack_01.cpp
- General Questions/intersection_of_arrays.c
- Numbers/Sieve-of-Eratosthenes.cpp
- Sorting Algorithms/insertion_sort.cpp
- Strings/Capitalizing.py
- Trie/Trie_add_Search_using_dict.py
Fixes:
- Should read `whatever` rather than `whaterever`.
- Should read `whether` rather than `wheather`.
- Should read `variable` rather than `varible`.
- Should read `traversing` rather than `travsersing`.
- Should read `splitting` rather than `spliiting`.
- Should read `something` rather than `soomething`.
- Should read `represent` rather than `represant`.
- Should read …

docs: Fix a few typos

---

DSA 450 GFG/ActivitySelection.py

Python solution for activity selection in DSA 450

---

DSA 450 GFG/LongestCommonPrefix.py

Yes
Link : https://leetcode.com/problems/longest-common-prefix/submissions/ 
Approach : 
Example
Input: strs = ["flower","flow","flight"]
Output: "fl"
We are supposed to return the longest common prefix  
Variables : 
prefix => longest common prefix
1. Assume the longest common substring to be the first element of the list . prefix = strs[0]
2. Iterate through the list of words and keep comparing each char of the word with the prefix 
3. If the char of word != char of prefix , reduce the prefix to last matched char
4. If the word is shorter than the prefix , and all charachters are matched , then prefix = word
Working
prefix = "flower"
i = 1
prefix = "flower" , word = "flow"
f = f , pass
l = l , pass 
o = o , pass
w = w , pass
i = 4 , 4 >= len("flow") , prefix = "flow"  , break
i = 2 …

Python solution for longest common prefix -- DSA450

---

Bit Manipulation/Power_Set_using_Bit_Manipulation.cpp

Yes, I have read all the Guidelines.
Issue #917
The problem that I have added wasn't there in the Bit Manipulation section, I am sure that it is fully optimized. It's name is Power Set using Bit Manipulation
Issue: #917 

Power Set using Bit Manipulation

---

DSA 450 GFG/WordBreak.py

Python soln for Word Break - DP approach
